/**
 * Checks the generated church calendar against the ELCF's official
 * perikooppikalenterit (church years 2021–2029).
 *
 * Fixture: test/fixtures/perikooppikalenterit.json, generated by
 * parsers/parse-perikooppikalenteri.js from refs/perikooppikalenterit/*.doc.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  generateChurchYear, getYearCycle, weekdayMaterialSlug, makeDate, formatDate, addDays,
} from '../src/computus.js';
import { resolveDate } from '../src/resolver.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(join(__dirname, 'fixtures', 'perikooppikalenterit.json'), 'utf-8'));

/** "7.–10.12.2022", "27.3.–1.4.2023", "2.1.2027" → ['2022-12-07', …] */
function expandRange(range) {
  const m = range.match(/^(\d{1,2})\.(?:(\d{1,2})\.)?(?:–(\d{1,2})\.(\d{1,2})\.)?(\d{4})$/);
  assert.ok(m, `Unparsable range ${range}`);
  const [, d1, m1, d2, m2, y] = m;
  const endMonth = Number(m2 ?? m1);
  const end = makeDate(Number(y), endMonth, Number(d2 ?? d1));
  let start = makeDate(Number(y), Number(m1 ?? endMonth), Number(d1));
  if (start > end) start = makeDate(Number(y) - 1, Number(m1 ?? endMonth), Number(d1));
  const days = [];
  for (let d = start; d <= end; d = addDays(d, 1)) days.push(d);
  return days;
}

/** Genitive material name from a weekday note → slug. */
function materialSlug(material) {
  const text = material.replace(/\(.*?\)/g, '').trim().toLowerCase();
  const fixed = {
    'joulupäivän': 'joulupaiva',
    'loppiaisen': 'loppiainen',
    'tuhkakeskiviikon': 'tuhkakeskiviikko',
    '1. adventtisunnuntain jälkeisen viikon': '1-adventtisunnuntain-jalkeinen-viikko',
  };
  if (fixed[text]) return fixed[text];
  let m = text.match(/^(\d+)\. adventtisunnuntain$/);
  if (m) return `${m[1]}-adventtisunnuntai`;
  m = text.match(/^(\d+)\. paastonajan sunnuntain$/);
  if (m) return `${m[1]}-paastonajan-sunnuntai`;
  m = text.match(/^(\d+)\. sunnuntain (joulusta|loppiaisesta|helluntaista|pääsiäisestä|ennen paastonaikaa)$/);
  if (m) return `${m[1]}-sunnuntai-${m[2].replace(/ä/g, 'a').replace(/ /g, '-')}`;
  throw new Error(`Unknown material: ${material}`);
}

for (const [startYear, year] of Object.entries(fixture.churchYears)) {
  const start = Number(startYear);

  describe(`Church year ${start}–${start + 1} (perikooppikalenteri)`, () => {
    const calendar = generateChurchYear(start);

    it(`is year cycle ${year.yearCycle}`, () => {
      assert.equal(getYearCycle(start), year.yearCycle);
    });

    it('starts and ends on the official dates', () => {
      assert.equal(calendar[0].dateStr, year.start);
      assert.ok(calendar.at(-1).dateStr <= year.end);
    });

    it('has every dated holy day on the official date', () => {
      const generated = new Set(calendar.filter(e => e.type !== 'weekday').map(e => `${e.dateStr} ${e.name}`));
      const official = new Set();
      for (const e of year.entries) {
        if (e.start !== e.end) continue; // weeks are checked below
        official.add(`${e.start} ${e.name}`);
      }
      const missing = [...official].filter(x => !generated.has(x));
      const extra = [...generated].filter(x => !official.has(x));
      assert.deepEqual({ missing, extra }, { missing: [], extra: [] });
    });

    it('covers weeks with their own weekday material', () => {
      for (const e of year.entries.filter(x => x.start !== x.end)) {
        for (let d = new Date(e.start); formatDate(d) <= e.end; d = addDays(d, 1)) {
          const onDate = calendar.filter(x => x.dateStr === formatDate(d)).map(x => x.name);
          assert.ok(onDate.includes(e.name), `${formatDate(d)} should include ${e.name}, got ${onDate}`);
        }
      }
    });

    it('uses the official material on weekdays ("Arkipäivinä … käytetään")', () => {
      for (const note of year.weekdayNotes) {
        const expected = materialSlug(note.material);
        for (const date of expandRange(note.range)) {
          const own = calendar.find(x => x.dateStr === formatDate(date) && x.type === 'weekday');
          const actual = own ? own.slug : weekdayMaterialSlug(calendar, date);
          assert.equal(actual, expected, `${formatDate(date)} (${note.range})`);
        }
      }
    });

    it('returns the official gospel for Sundays and holy days', () => {
      const mismatches = [];
      for (const e of year.entries) {
        if (e.start !== e.end || !e.readings.gospel) continue;
        const resolved = resolveDate(e.start);
        const days = [resolved.holyDay, ...(resolved.additionalServices || [])].filter(Boolean);
        const day = days.find(d => d.name === e.name);
        if (!day) { mismatches.push(`${e.start} ${e.name}: not resolved`); continue; }
        const gospel = day.texts?.gospel?.reference?.replace(/--/g, '–');
        const official = e.readings.gospel.map(g => g.replace(/-/g, '–'));
        if (!official.includes(gospel)) {
          mismatches.push(`${e.start} ${e.name}: got ${gospel}, expected ${e.readings.gospel.join(' / ')}`);
        }
      }
      assert.deepEqual(mismatches, []);
    });

    it('returns the official readings, psalm and hallelujah verse', () => {
      // Punctuation differs between the two publications ("Ap.t." / "Ap. t.", "Job." / "Job", ";" / ",")
      const norm = ref => ref?.replace(/[-–]+/g, '–').replace(/[\s.]+/g, '').replace(/;/g, ',').replace(/(Job)(\d)/, '$1$2').trim();
      const mismatches = [];
      for (const e of year.entries) {
        if (e.start !== e.end) continue;
        const resolved = resolveDate(e.start);
        const day = [resolved.holyDay, ...resolved.additionalServices].find(d => d?.name === e.name);
        if (!day) continue; // reported by the gospel test
        const check = (label, official, actual) => {
          // Apocryphal verses are cited differently ("Dan. 3:52 (apokr.)" / "Dan. lis. C:52")
          if (!official?.length || official.some(o => /apokr/.test(o))) return;
          const expected = official.flatMap(o => o.split(' tai ')).map(norm);
          if (!expected.includes(norm(actual))) mismatches.push(`${e.start} ${e.name} ${label}: got ${actual}, expected ${expected.join(' / ')}`);
        };
        check('1. lukukappale', e.readings.firstReading, day.texts?.firstReading?.reference);
        check('2. lukukappale', e.readings.secondReading, day.texts?.secondReading?.reference);
        check('psalmi', e.readings.psalm, day.psalm?.reference);
        check('hallelujasäe', e.readings.hallelujah, day.hallelujah?.reference);
        check('psalmilause', e.readings.psalmVerse, day.psalmVerse?.reference);
      }
      assert.deepEqual(mismatches, []);
    });
  });
}
